apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mysql-secret.yaml
  - persistent-volume.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - wordpress-deployment.yaml
  - wordpress-service.yaml